steps:

- label: xrefcheck
  commands:
  - nix run github:serokell/xrefcheck

- label: reuse
  commands:
  - nix build -L .#checks.x86_64-linux.reuse-lint

- label: hlint
  commands:
  - nix build -L .#checks.x86_64-linux.hlint

- label: stylish-haskell
  commands:
  - nix build -L .#checks.x86_64-linux.stylish-haskell

- label: check-trailing-whitespace
  commands:
  - nix build -L .#checks.x86_64-linux.trailing-whitespace

# - label: check-stack2cabal
#   commands:
#   - nix develop .#ci -c bash -c 'stack2cabal && git add -A && git diff HEAD --exit-code'

# - label: check-hpack
#   commands:
#   - nix build -L .#checks.x86_64-linux.hpack

# build haskell components
- label: build
  commands:
  - nix-build -A checks.x86_64-linux.build-all

# don't run tests until all components are built
- wait

# run the tests
- label: test
  commands:
  - nix-build -A checks.x86_64-linux.test
