name: Nix flake check
on:
  pull_request:
  push:
    # If your is default branch is 'main' delete the next line and uncomment the line following it
    branches: master
    # branches: main

jobs:
  validate:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4

      - name: xrefcheck
        run: nix run github:serokell/xrefcheck

      - name: reuse
        run: nix build -L .#checks.x86_64-linux.reuse-lint
        # Run step even if the previous one has failed
        if: success() || failure()

      - name: hlint
        run: nix build -L .#checks.x86_64-linux.hlint
        if: success() || failure()

      - name: stylish-haskell
        run: nix build -L .#checks.x86_64-linux.stylish-haskell
        if: success() || failure()

      - name: check-trailing-whitespace
        run: nix build -L .#checks.x86_64-linux.trailing-whitespace
        if: success() || failure()

      # - name: cabal-check
      #   run: nix build -L .#checks.x86_64-linux.cabal-check
      #   if: success() || failure()

      # - name: check-stack2cabal
      #   run: nix develop .#ci -c bash -c 'stack2cabal && git add -A && git diff HEAD --exit-code'
      #   if: success() || failure()

      # - name: check-hpack
      #   run: nix build -L .#checks.x86_64-linux.hpack
      #   if: success() || failure()

      # - name: check-weeder
      #   run: nix build -L .#checks.x86_64-linux.weeder
      #   if: success() || failure()

  build:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4

      - name: build-all
        run: nix build -L .#checks.x86_64-linux.build-all --keep-going

  test:
    runs-on: [self-hosted, nix]
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: test
        run: nix build -L .#checks.x86_64-linux.test
