steps:

- label: xrefcheck
  commands:
  - nix run github:serokell/xrefcheck

- label: reuse
  commands:
  - nix build -L .#checks.x86_64-linux.reuse-lint

- label: hlint
  commands:
  - nix build -L .#checks.x86_64-linux.hlint

- label: stylish-haskell
  commands:
  - nix build -L .#checks.x86_64-linux.stylish-haskell

- label: check-trailing-whitespace
  commands:
  - nix build -L .#checks.x86_64-linux.trailing-whitespace

# - label: shellcheck
#   commands:
#   - nix build -L .#checks.x86_64-linux.shellcheck

# - label: check-stack2cabal
#   commands:
#   - nix develop .#ci -c bash -c 'stack2cabal && git add -A && git diff HEAD --exit-code'

# - label: check-hpack
#   commands:
#   - nix build -L .#checks.x86_64-linux.hpack

# build haskell components
- group: build
  steps:
    - label: {{matrix}}
      command: nix build -L .#checks.x86_64-linux.${{ matrix }}:build-all --keep-going

      # list of check prefixes for haskell components
      matrix: &build-matrix
        # ghc versions
        - "ghc884"
        - "ghc8107"
        - "ghc902"
        # stack files and resolvers
        # NOTE: all dots should be replaced with dashes
        - "stack-yaml"
        - "stack-lts-21-5-yaml"
        - "lts-19-13"


# don't run tests until all components are built
- wait

# run the tests
- group: test
  steps:
    - label: {{matrix}}
      command: nix build -L .#checks.x86_64-linux.${{ matrix }}:test-all --keep-going

      matrix: *build-matrix
