default:
  # specify nix tag to select runner
  tags: [nix]

stages:
  - validate
  - build
  - test

xrefcheck:
  stage: validate
  script:
    - nix run github:serokell/xrefcheck

reuse:
  stage: validate
  script:
    - nix build -L .#checks.x86_64-linux.reuse-lint

hlint:
  stage: validate
  script:
    - nix build -L .#checks.x86_64-linux.hlint

stylish-haskell:
  stage: validate
  script:
    - nix build -L .#checks.x86_64-linux.stylish-haskell

check-trailing-whitespace:
  stage: validate
  script:
    - nix build -L .#checks.x86_64-linux.trailing-whitespace

# cabal-check:
#   stage: validate
#   script:
#     - nix build -L .#checks.x86_64-linux.cabal-check

# check-stack2cabal:
#   stage: validate
#   script:
#     - nix develop .#ci -c bash -c 'stack2cabal && git add -A && git diff HEAD --exit-code'

# check-hpack:
#   stage: validate
#   script:
#     - nix build -L .#checks.x86_64-linux.hpack

# check-weeder:
#   stage: validate
#   script:
#     - nix build -L .#checks.x86_64-linux.weeder

# build haskell components
build-all:
  stage: build
  script:
  - nix build -L .#checks.x86_64-linux.build-all

# run the tests
test:
  stage: test
  script:
  - nix build -L .#checks.x86_64-linux.test
