on:
  schedule:
    # runs every Monday at 10:00 am UTC
    - cron: '0 10 * * 1'

jobs:
  check-outdated:
    runs-on: [self-hosted, nix]
    outputs:
      msg: ${{ steps.outdated.outputs.outdated }}
    steps:
      - uses: actions/checkout@v4

      - name: check outdated packages
        id: outdated
        run: |
          function output {
            echo "outdated<<EOF" >> $GITHUB_OUTPUT
            echo "Repository https://github.com/${{ github.repository }} has outdated haskell dependencies" >> $GITHUB_OUTPUT
            echo "$msg" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          }

          nix develop .#ci -c cabal update
          trap 'output' ERR
          msg=$(nix develop .#ci -c cabal outdated --exit-code)

  report-outdated:
    runs-on: [self-hosted, nix]
    if: failure()
    needs: check-outdated
    steps:
      - uses: actions/checkout@v4

      - name: Report outdated haskell dependencies
        env:
          SLACK_TOKEN: ${{ env.SLACK_TOKEN }}
          # you can change 'libraries' to the channel dedicated to the library, if there is one
          # in order for a bot to be able to post messages, it must be added to the appropriate channel
          SLACK_CHANNEL: "libraries"
          MESSAGE: ${{needs.check-outdated.outputs.msg}}
        run: |
          ./scripts/slack-send-message.sh
